services:
  workspace:
      build:
          context: .
          dockerfile: Dockerfile
      volumes:
          - ..:/workspace:cached
      command: sleep infinity
  
  redis:
    image: redis:alpine
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example